// Generated by https://quicktype.io

class Reservation {
  late int id;
  late String amount;
  late int status;
  late int clientId;
  late int boatId;
  late List reservedDays;
  late List moves;

  Reservation({
    required this.id,
    required this.amount,
    required this.status,
    required this.clientId,
    required this.boatId,
    required this.reservedDays,
    required this.moves,
  });

  Reservation.fromJson(json) {
    id = json['id'];
    amount = json['amount'];
    status = json['status'];
    clientId = json['client_id'];
    boatId = json['boat_id'];
    reservedDays = json['reserved_days'];
    moves = json['moves'];
  }
}
